name: CI

on: 
  workflow_dispatch:
jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: build binary
      run: |
        docker build . -t builder
        docker run --rm -v ${PWD}:/project builder make dist
    - uses: actions/upload-artifact@v4
      with:
       name: Bloopair_nightly
       path: dist/*
